# Generated by Django 4.2.6 on 2023-10-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acaiAplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formadeenvio',
            name='custo',
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.BooleanField(verbose_name='Em Estoque'),
        ),
    ]
