# Generated by Django 4.2.6 on 2023-10-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acaiAplic', '0002_remove_formadeenvio_custo_alter_produto_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formadeenvio',
            name='prazo_entrega',
        ),
    ]
