# Generated by Django 4.2.6 on 2023-10-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acaiAplic', '0003_remove_formadeenvio_prazo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acaiAplic.produto'),
        ),
    ]
