# Generated by Django 4.2.6 on 2023-10-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acaiAplic', '0004_pedido_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
    ]
