# Generated by Django 4.2.6 on 2023-10-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acaiAplic', '0005_remove_pedido_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item Pedido', 'verbose_name_plural': 'Itens Pedido'},
        ),
    ]
