# Generated by Django 4.2.6 on 2023-10-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acaiAplic', '0007_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='formaDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix')], default='Cartão', max_length=15)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acaiAplic.cliente')),
            ],
        ),
    ]
