# Generated by Django 4.2.6 on 2023-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acaiAplic', '0011_formadepagamento_numcartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
